Stackpole/Models/ScrapDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stackpole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapDetail
    {
        public int id { get; set; }
        public int scrapId { get; set; }
        public int reasonId { get; set; }
        public int machineId { get; set; }
        public int quantity { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<short> employeeNumber { get; set; }
    }
}

Stackpole/ViewModels/DeleteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stackpole.ViewModels
{
    public class DeleteViewModel
    {
        public int scrapDetailId { get; set; }
        public int operationId { get; set; }
    }
}

Stackpole/ViewModels/ScrapDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using Stackpole.Models;

namespace Stackpole.ViewModels
{
    public class ScrapDetailViewModel : IObjectWithState
    {
        public int id { get; set; }
        public int scrapId { get; set; }
        public int reasonId { get; set; }
        public int machineId { get; set; }
        public int quantity { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<short> employeeNumber { get; set; }


        public ObjectState ObjectState { get; set; }
    }
}

Stackpole/Controllers/ScrapDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Stackpole.Models;
using Stackpole.ViewModels;

namespace Stackpole.Controllers
{
    public class ScrapDetailsController : Controller
    {
        private StackpoleEntities _stackpoleContext;

        public ScrapDetailsController()
        {
            _stackpoleContext = new StackpoleEntities();
        }

        // GET: ScrapDetails
        public ActionResult Index(string plantName, 
                                    string departmentName, 
                                    string partId, 
                                    string operationName, 
                                    int operationId,
                                    double? weight,
                                    double? cost,
                                    int? scrapId = 0
            )
        {
            ViewBag.departmentName = departmentName;
            ViewBag.plantName = plantName;
            ViewBag.partId = partId;
            ViewBag.operationName = operationName;
            ViewBag.operationId = operationId;
            ViewBag.unitWeight = weight;
            ViewBag.unitCost = cost;

            ViewBag.date = DateTime.Now;
            ViewBag.scrapId = 0;

            // NOTE: once one new scrap is added
            // then we want to display that scrap with its details (scrap details) again
            // everytime the page is refreshed
            if (scrapId != 0)
            {
                ViewBag.scrapId = scrapId;

                // initialize the scrap details
                ScrapsViewModel scrapsViewModel = new ScrapsViewModel();

                scrapsViewModel.scrap = _stackpoleContext.Scraps
                                        .Where(s => s.id == scrapId)
                                        .OrderByDescending(s => s.date)
                                        .FirstOrDefault();

                //var scrapDetails = db.ScrapDetails.Include(s => s.ScrapReason).Include(s => s.Scrap);
                if (scrapsViewModel.scrap != null)
                {
                    scrapsViewModel.scrapDetails = _stackpoleContext.ScrapDetails
                                        .Where(sd => sd.scrapId == scrapsViewModel.scrap.id)
                                        .ToList();
                }

                return View(scrapsViewModel);
            }

            return View();
        }

        public ActionResult IndexForUpdate(string plantName,
                                    string departmentName,
                                    string partId,
                                    string operationName,
                                    int operationId,
                                    double? weight,
                                    double? cost,
                                    int? scrapId = 0)
        {
            ViewBag.departmentName = departmentName;
            ViewBag.plantName = plantName;
            ViewBag.partId = partId;
            ViewBag.operationName = operationName;
            ViewBag.operationId = operationId;
            ViewBag.unitWeight = weight;
            ViewBag.unitCost = cost;
            ViewBag.date = DateTime.Now;
            ViewBag.scrapId = 0;

            ScrapViewModel scrapViewModel = new ScrapViewModel();
            scrapViewModel.plantId = plantName;
            scrapViewModel.departmentId = departmentName;
            scrapViewModel.partId = partId;
            scrapViewModel.operationId = operationName;
            scrapViewModel.unitWeight = weight;
            scrapViewModel.unitCost = cost;
            scrapViewModel.date = System.DateTime.Now;
            scrapViewModel.ObjectState = ObjectState.Added;

            getLisMachinesForEdit(partId, departmentName, operationName);

            return View(scrapViewModel);
        }

        [HttpPost]
        public ActionResult CreateNewScrapModal(ScrapBasicInfoModal scrapBasicInfoModal)
        {
            // initialize data for drop down list in create view
            //getDropDownList(scrapBasicInfoModal.operationIdInt);
            getDropDownListForCreateScrap(scrapBasicInfoModal.operationIdInt, scrapBasicInfoModal);

            // NOTE: avoid error when saving as null value 
            // we should init values as 0 before passing them to the view
            scrapBasicInfoModal.scrapDetailModal.quantity = 0;
            scrapBasicInfoModal.scrapDetailModal.weight = 0;

            return PartialView("_CreateNewScrapModal", scrapBasicInfoModal);
        }

        // POST: ScrapDetails/CreateNewScrapPostModal
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "id,scrapId,reasonId,machineId,quantity,weight,cost,employeeNumber")] ScrapDetail scrapDetail)
        //public ActionResult CreateNewScrapPost([Bind(Include = "reasonId,machineId,quantity,weight,cost,employeeNumber")] ScrapBasicInfo scrapBasicInfo)
        public ActionResult CreateNewScrapPostModal(ScrapBasicInfoModal scrapBasicInfoModal)
        {
            if (ModelState.IsValid)
            {
                Scrap scrap = new Scrap();

                /* case add first new scrap */
                if (scrapBasicInfoModal.scrapDetailModal.scrapId == 0)
                {
                    scrap.date = scrapBasicInfoModal.scrapModal.date;
                    scrap.machineId = scrapBasicInfoModal.scrapDetailModal.machineId;
                    scrap.operationId = scrapBasicInfoModal.scrapModal.operationId;
                    scrap.partId = scrapBasicInfoModal.scrapModal.partId;
                    scrap.plantId = scrapBasicInfoModal.scrapModal.plantId;
                    scrap.unitCost = scrapBasicInfoModal.scrapModal.unitCost;
                    scrap.unitWeight = scrapBasicInfoModal.scrapModal.unitWeight;
                    scrap.departmentId = scrapBasicInfoModal.scrapModal.departmentId;
                    //scrap.cancelled = false;

                    _stackpoleContext.Scraps.Add(scrap);
                    _stackpoleContext.SaveChanges();

                    scrapBasicInfoModal.scrapModal.id = scrap.id;
                    scrapBasicInfoModal.scrapDetailModal.scrapId = scrap.id;
                }

                ScrapDetail scrapDetail = new ScrapDetail();
                scrapDetail.scrapId = scrapBasicInfoModal.scrapDetailModal.scrapId;
                scrapDetail.reasonId = scrapBasicInfoModal.scrapDetailModal.reasonId;
                scrapDetail.machineId = scrapBasicInfoModal.scrapDetailModal.machineId;
                scrapDetail.quantity = scrapBasicInfoModal.scrapDetailModal.quantity;
                scrapDetail.weight = scrapBasicInfoModal.scrapDetailModal.weight;
                scrapDetail.cost = scrapBasicInfoModal.scrapDetailModal.cost;
                scrapDetail.employeeNumber = scrapBasicInfoModal.scrapDetailModal.employeeNumber;
                
                _stackpoleContext.ScrapDetails.Add(scrapDetail);
                _stackpoleContext.SaveChanges();

                //Index(string plantName, string departmentName, string partId, string operationName, int operationId)
                return RedirectToAction("Index", new
                {
                    plantName = scrapBasicInfoModal.scrapModal.plantId,
                    departmentName = scrapBasicInfoModal.scrapModal.departmentId,
                    partId = scrapBasicInfoModal.scrapModal.partId,
                    operationName = scrapBasicInfoModal.scrapModal.operationId,
                    operationId = scrapBasicInfoModal.operationIdInt,
                    weight = scrapBasicInfoModal.scrapModal.unitWeight,
                    cost= scrapBasicInfoModal.scrapModal.unitCost,
                    scrapId = scrapBasicInfoModal.scrapDetailModal.scrapId
                });
            }
            var errors = ModelState
                            .Where(x => x.Value.Errors.Count > 0)
                            .Select(x => new { x.Key, x.Value.Errors })
                            .ToArray();

            //ViewBag.scrapID = new SelectList(db.Scraps, "id", "partId", scrapDetail.scrapId);
            //ViewBag.machineId = new SelectList(db.Scraps, "id", "partId", scrapDetail.scrapId);
            //ViewBag.reasonID = new SelectList(db.ScrapReasons, "id", "description", scrapDetail.reasonId);
            //return View(scrapDetail);

            //return View();
            return PartialView("_CreateNewScrapModal", scrapBasicInfoModal);
        }

        [HttpPost]
        public ActionResult CancelEntry(int? scrapId)
        {
            return PartialView("_CancelEntry", scrapId);
        }

        [HttpPost]
        public ActionResult CancelEntrySubmit(int? scrapId)
        {
            Scrap scrap = _stackpoleContext.Scraps.Where(s => s.id == scrapId).FirstOrDefault();
            scrap.cancelled = "c";
            _stackpoleContext.Entry(scrap).State = EntityState.Modified;
            _stackpoleContext.SaveChanges();

            return RedirectToAction("Index", "Operations", new
            {
                plantName = scrap.plantId,
                departmentName = scrap.departmentId,
                partId = scrap.partId,
                weight = scrap.unitWeight,
                cost = scrap.unitCost
            });
        }

        private void getDropDownListForEditScrap(int? operationId, ScrapDetail scrapDetail = null)
        {
            // get data for drop down list of machines
            var getMachNumber = _stackpoleContext.qryMachNumbers
                                    .Where(m => m.OperationID == operationId)

Stackpole/Views/ScrapDetails/CreateNewScrap.cshtml
@model Stackpole.ViewModels.ScrapBasicInfo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("CreateNewScrapPost", "ScrapDetails"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>ScrapDetail</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @*@Html.HiddenFor(model => model.scrapDetail.id)
        @Html.HiddenFor(model => model.scrapDetail.scrapId)*@

    @Html.HiddenFor(m => m.scrap.plantId)
    @Html.HiddenFor(m => m.scrap.departmentId)
    @Html.HiddenFor(m => m.scrap.operationId)
    @Html.HiddenFor(m => m.operationIdInt)
    @Html.HiddenFor(m => m.scrap.partId)
    @Html.HiddenFor(m => m.scrap.unitCost)
    @Html.HiddenFor(m => m.scrap.unitWeight)
    @Html.HiddenFor(m => m.scrap.date)

    @*<div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.scrapId, "scrapId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("scrapId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.scrapId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.machineID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.machineID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.machineID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reasonID, "reasonID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("reasonID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.reasonID, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.scrapDetail.machineId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("machineId", null, string.Empty, htmlAttributes: new { @class = "form-control", Name = "scrapDetail.machineId" })
            @Html.ValidationMessageFor(model => model.scrapDetail.machineId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.scrapDetail.reasonId, "reasonId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("reasonId", null, string.Empty, htmlAttributes: new { @class = "form-control reason-content", Name = "scrapDetail.reasonId", @onchange = "selectReason(this.value)" })
            @Html.ValidationMessageFor(model => model.scrapDetail.reasonId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group quantity">
        @Html.LabelFor(model => model.scrapDetail.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.scrapDetail.quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.scrapDetail.quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group weight">
        @Html.LabelFor(model => model.scrapDetail.weight, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.scrapDetail.weight, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.scrapDetail.weight, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group cost">
        @Html.LabelFor(model => model.scrapDetail.cost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.scrapDetail.cost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.scrapDetail.cost, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.scrapDetail.employeeNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.scrapDetail.employeeNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.scrapDetail.employeeNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
    @Html.ActionLink("Back to List", null, null, null, new { href = Request.UrlReferrer })
</div>

@section scripts {
    <script type="text/javascript" src="~/Scripts/Stackpole/scrapDetail.js"></script>
}

Stackpole/Views/ScrapDetails/Delete.cshtml
@model Stackpole.Models.ScrapDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ScrapDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.machineId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.machineId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.employeeNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employeeNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ScrapReason.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ScrapReason.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Scrap.partId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Scrap.partId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to list", null, null, null, new { href = Request.UrlReferrer })
    </div>
    }
</div>

Stackpole/Views/ScrapDetails/Details.cshtml
@model Stackpole.Models.ScrapDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ScrapDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.machineID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.machineID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.employeeNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employeeNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ScrapReason.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ScrapReason.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Scrap.partId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Scrap.partId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Stackpole/Views/ScrapDetails/Index.cshtml
@model Stackpole.ViewModels.ScrapsViewModel

@Styles.Render("~/Content/scrap")

@{
    ViewBag.Title = "Scrap Details";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">@ViewBag.partId</a></li>
        <li class="breadcrumb-item"><a href="#">@ViewBag.departmentName</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewBag.operationName</li>
    </ol>
</nav>

<h2>@((DateTime)ViewBag.date)</h2>

<h4>Unit cost:      @ViewBag.unitCost</h4>
<h4>Unit weight:    @ViewBag.unitWeight</h4>

@*DON'T DELETE THIS - THIS IS ANOTHER TECHNIQUE TO PASS DATA TO VIEW*@
@*<p>
        @using (Html.BeginForm("CreateNewScrap", "ScrapDetails", FormMethod.Post))
        {
            @Html.HiddenFor(m => m.scrap.plantId, new { @Value = ViewBag.plantName })
            @Html.HiddenFor(m => m.scrap.departmentId, new { @Value = ViewBag.departmentName })
            @Html.HiddenFor(m => m.scrap.operationId, new { @Value = ViewBag.operationName })
            @Html.HiddenFor(m => m.operationIdInt, new { @Value = ViewBag.operationId })
            @Html.HiddenFor(m => m.scrap.partId, new { @Value = ViewBag.partId })
            @Html.HiddenFor(m => m.scrap.unitCost, new { @Value = ViewBag.unitCost })
            @Html.HiddenFor(m => m.scrap.unitWeight, new { @Value = ViewBag.unitWeight })
            @Html.HiddenFor(m => m.scrap.date, new { @Value = ViewBag.date })

            @Html.HiddenFor(m => m.scrap.machineId, new { @Value = ViewBag.machineId })

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create New Scrap" class="btn btn-default" />
                </div>
            </div>
        }
    </p>*@

    <button type="button"
            class="btn btn-primary btn-add-scrap"
            data-date="@ViewBag.date"
            data-operationId="@ViewBag.operationId"
            data-operationName="@ViewBag.operationName"
            data-partId="@ViewBag.partId"
            data-plantId="@ViewBag.plantName"
            data-unitCost="@ViewBag.unitCost"
            data-unitWeight="@ViewBag.unitWeight"
            data-departmentId="@ViewBag.departmentName"
            data-scrapid="@ViewBag.scrapId">
        Add scrap
    </button>

    @Html.ActionLink("Finished with This Part", "Index", "Home", null, new { @class = "btn btn-primary", style= "background-color: #688632;" })

    @*@Html.ActionLink("Cancel Entry", "Edit", new { })*@
    <button type="button"
            class="btn btn-primary btn-cancel-entry"
            data-scrapid="@ViewBag.scrapId"
            data-operationid="@ViewBag.operationId">
        Cancel Entry
    </button>

<table class="table">
    <tr>
        <th>
            Machine
        </th>
        <th>
            Scrap Reason
        </th>
        <th>
            Quantity
        </th>
        <th>
            Value
        </th>
        <th>
            Weight
        </th>
        <th>
            Employee #
        </th>
        <th></th>
    </tr>

    @if (Model != null && Model.scrapDetails != null)
    {
        foreach (var item in Model.scrapDetails)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.machineId)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.ScrapReason.description)*@
                    @Html.DisplayFor(modelItem => item.reasonId)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.employeeNumber)
                </td>

                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { scrapId = item.scrapId, operationId = ViewBag.operationId, r = Request.Url.ToString() }) |*@
                    <button type="button"
                            class="btn btn-info btn-edit-scrap"
                            data-scrapdetailid="@item.id"
                            data-scrapid="@item.scrapId"
                            data-operationid="@ViewBag.operationId"
                            data-reasonid="@item.reasonId">
                        Edit scrap
                    </button> |
                    @*@Html.ActionLink("Details", "Details", new { id = item.id }) |*@
                    @*@Html.ActionLink("Delete", "Delete", new { scrapId = item.scrapId })*@
                    <button type="button"
                            class="btn btn-info btn-delete-scrap"
                            data-scrapdetailid="@item.id"
                            data-operationid="@ViewBag.operationId">
                        Delete
                    </button>

                </td>
            </tr>
        }
    }
</table>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>

@section scripts {
    <script src="/scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="/scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/Scripts/Stackpole/scrap.js"></script>
    <script type="text/javascript" src="~/Scripts/Stackpole/scrapDetail.js"></script>
}

Stackpole/Views/ScrapDetails/_CancelEntry.cshtml
@model  int?

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Scrap Reporting System</h4>
</div>

<div class="modal-body">
    @if (Model == 0)
    {
        <p>Nothing to cancel!</p>
    }
    else
    {
        <p>Are you sure you wish to cancel?</p>
    }
</div>

<div class="modal-footer">
    @if (Model == 0)
    {
        <button type="button" class="btn btn-primary" data-dismiss="modal" id="modal-btn-ok">OK</button>
    }
    else
    {
        using (Html.BeginForm("CancelEntrySubmit", "ScrapDetails", new { scrapId = Model }))
        {
            <button type="submit" class="btn btn-default" id="modal-btn-yes">Yes</button>
            <button type="button" class="btn btn-primary" data-dismiss="modal" id="modal-btn-no">No</button>
        }
    }
</div>

Stackpole/Views/ScrapDetails/_DeleteConfirm.cshtml
@model  Stackpole.ViewModels.DeleteViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Scrap Reporting System</h4>
</div>

<div class="modal-body">
    <p>Are you sure you wish to delete?</p>
</div>

<div class="modal-footer">
    @using (Html.BeginForm("DeleteConfirmed", "ScrapDetails"))
    {
        @Html.HiddenFor(model => model.scrapDetailId)
        @Html.HiddenFor(model => model.operationId)

        <button type="submit" class="btn btn-default" id="modal-btn-yes">Yes</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal" id="modal-btn-no">No</button>
    }
</div>